--
-- PostgreSQL database dump
--

-- Dumped from database version 14.5
-- Dumped by pg_dump version 14.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: dlk_torrecontrol; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA dlk_torrecontrol;


ALTER SCHEMA dlk_torrecontrol OWNER TO postgres;

--
-- Name: dwh_torrecontrol; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA dwh_torrecontrol;


ALTER SCHEMA dwh_torrecontrol OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: AspNetRoleClaims; Type: TABLE; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE TABLE dlk_torrecontrol."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE dlk_torrecontrol."AspNetRoleClaims" OWNER TO postgres;

--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE dlk_torrecontrol."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dlk_torrecontrol."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetRoles; Type: TABLE; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE TABLE dlk_torrecontrol."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE dlk_torrecontrol."AspNetRoles" OWNER TO postgres;

--
-- Name: AspNetUserClaims; Type: TABLE; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE TABLE dlk_torrecontrol."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE dlk_torrecontrol."AspNetUserClaims" OWNER TO postgres;

--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE dlk_torrecontrol."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dlk_torrecontrol."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetUserLogins; Type: TABLE; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE TABLE dlk_torrecontrol."AspNetUserLogins" (
    "LoginProvider" character varying(128) NOT NULL,
    "ProviderKey" character varying(128) NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


ALTER TABLE dlk_torrecontrol."AspNetUserLogins" OWNER TO postgres;

--
-- Name: AspNetUserRoles; Type: TABLE; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE TABLE dlk_torrecontrol."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


ALTER TABLE dlk_torrecontrol."AspNetUserRoles" OWNER TO postgres;

--
-- Name: AspNetUserTokens; Type: TABLE; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE TABLE dlk_torrecontrol."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" character varying(128) NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Value" text
);


ALTER TABLE dlk_torrecontrol."AspNetUserTokens" OWNER TO postgres;

--
-- Name: AspNetUsers; Type: TABLE; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE TABLE dlk_torrecontrol."AspNetUsers" (
    "Id" text NOT NULL,
    "UsuarioNombre" character varying(255) NOT NULL,
    "UsuarioApellidos" character varying(255) NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE dlk_torrecontrol."AspNetUsers" OWNER TO postgres;

--
-- Name: Tdc_cat_estados_devolucion_pedido; Type: TABLE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE TABLE dwh_torrecontrol."Tdc_cat_estados_devolucion_pedido" (
    "Cod_estado_devolucion" text NOT NULL,
    "Md_uuid" text NOT NULL,
    "Md_date" timestamp without time zone NOT NULL,
    "Id" integer NOT NULL,
    "Des_estado_devolucion" text
);


ALTER TABLE dwh_torrecontrol."Tdc_cat_estados_devolucion_pedido" OWNER TO postgres;

--
-- Name: Tdc_cat_estados_devolucion_pedido_Id_seq; Type: SEQUENCE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE SEQUENCE dwh_torrecontrol."Tdc_cat_estados_devolucion_pedido_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE dwh_torrecontrol."Tdc_cat_estados_devolucion_pedido_Id_seq" OWNER TO postgres;

--
-- Name: Tdc_cat_estados_devolucion_pedido_Id_seq; Type: SEQUENCE OWNED BY; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER SEQUENCE dwh_torrecontrol."Tdc_cat_estados_devolucion_pedido_Id_seq" OWNED BY dwh_torrecontrol."Tdc_cat_estados_devolucion_pedido"."Id";


--
-- Name: Tdc_cat_estados_envio_pedido; Type: TABLE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE TABLE dwh_torrecontrol."Tdc_cat_estados_envio_pedido" (
    "Cod_estado_envio" text NOT NULL,
    "Md_uuid" text NOT NULL,
    "Md_date" timestamp without time zone NOT NULL,
    "Id" integer NOT NULL,
    "Des_estado_envio" text
);


ALTER TABLE dwh_torrecontrol."Tdc_cat_estados_envio_pedido" OWNER TO postgres;

--
-- Name: Tdc_cat_estados_envio_pedido_Id_seq; Type: SEQUENCE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE SEQUENCE dwh_torrecontrol."Tdc_cat_estados_envio_pedido_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE dwh_torrecontrol."Tdc_cat_estados_envio_pedido_Id_seq" OWNER TO postgres;

--
-- Name: Tdc_cat_estados_envio_pedido_Id_seq; Type: SEQUENCE OWNED BY; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER SEQUENCE dwh_torrecontrol."Tdc_cat_estados_envio_pedido_Id_seq" OWNED BY dwh_torrecontrol."Tdc_cat_estados_envio_pedido"."Id";


--
-- Name: Tdc_cat_estados_pago_pedido; Type: TABLE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE TABLE dwh_torrecontrol."Tdc_cat_estados_pago_pedido" (
    "Cod_estado_pago" text NOT NULL,
    "Md_uuid" text NOT NULL,
    "Md_date" timestamp without time zone NOT NULL,
    "Id" integer NOT NULL,
    "Des_estado_pago" text
);


ALTER TABLE dwh_torrecontrol."Tdc_cat_estados_pago_pedido" OWNER TO postgres;

--
-- Name: Tdc_cat_estados_pago_pedido_Id_seq; Type: SEQUENCE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE SEQUENCE dwh_torrecontrol."Tdc_cat_estados_pago_pedido_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE dwh_torrecontrol."Tdc_cat_estados_pago_pedido_Id_seq" OWNER TO postgres;

--
-- Name: Tdc_cat_estados_pago_pedido_Id_seq; Type: SEQUENCE OWNED BY; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER SEQUENCE dwh_torrecontrol."Tdc_cat_estados_pago_pedido_Id_seq" OWNED BY dwh_torrecontrol."Tdc_cat_estados_pago_pedido"."Id";


--
-- Name: Tdc_cat_lineas_distribucion; Type: TABLE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE TABLE dwh_torrecontrol."Tdc_cat_lineas_distribucion" (
    "Cod_linea" text NOT NULL,
    "Md_uuid" text NOT NULL,
    "Md_date" timestamp without time zone NOT NULL,
    "Id" integer NOT NULL,
    "Cod_provincia" text NOT NULL,
    "Cod_municipio" text NOT NULL,
    "Cod_barrio" text NOT NULL
);


ALTER TABLE dwh_torrecontrol."Tdc_cat_lineas_distribucion" OWNER TO postgres;

--
-- Name: Tdc_cat_lineas_distribucion_Id_seq; Type: SEQUENCE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE SEQUENCE dwh_torrecontrol."Tdc_cat_lineas_distribucion_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE dwh_torrecontrol."Tdc_cat_lineas_distribucion_Id_seq" OWNER TO postgres;

--
-- Name: Tdc_cat_lineas_distribucion_Id_seq; Type: SEQUENCE OWNED BY; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER SEQUENCE dwh_torrecontrol."Tdc_cat_lineas_distribucion_Id_seq" OWNED BY dwh_torrecontrol."Tdc_cat_lineas_distribucion"."Id";


--
-- Name: Tdc_tch_estado_pedidos; Type: TABLE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE TABLE dwh_torrecontrol."Tdc_tch_estado_pedidos" (
    "Id" integer NOT NULL,
    "Md_uuid" text NOT NULL,
    "Md_date" timestamp without time zone NOT NULL,
    "Cod_pedido" text NOT NULL,
    "Cod_estado_envio" text,
    "Cod_estado_pago" text,
    "Cod_estado_devolucion" text,
    "Cod_linea" text NOT NULL
);


ALTER TABLE dwh_torrecontrol."Tdc_tch_estado_pedidos" OWNER TO postgres;

--
-- Name: Tdc_tch_estado_pedidos_Id_seq; Type: SEQUENCE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE SEQUENCE dwh_torrecontrol."Tdc_tch_estado_pedidos_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE dwh_torrecontrol."Tdc_tch_estado_pedidos_Id_seq" OWNER TO postgres;

--
-- Name: Tdc_tch_estado_pedidos_Id_seq; Type: SEQUENCE OWNED BY; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER SEQUENCE dwh_torrecontrol."Tdc_tch_estado_pedidos_Id_seq" OWNED BY dwh_torrecontrol."Tdc_tch_estado_pedidos"."Id";


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Name: Tdc_cat_estados_devolucion_pedido Id; Type: DEFAULT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol."Tdc_cat_estados_devolucion_pedido" ALTER COLUMN "Id" SET DEFAULT nextval('dwh_torrecontrol."Tdc_cat_estados_devolucion_pedido_Id_seq"'::regclass);


--
-- Name: Tdc_cat_estados_envio_pedido Id; Type: DEFAULT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol."Tdc_cat_estados_envio_pedido" ALTER COLUMN "Id" SET DEFAULT nextval('dwh_torrecontrol."Tdc_cat_estados_envio_pedido_Id_seq"'::regclass);


--
-- Name: Tdc_cat_estados_pago_pedido Id; Type: DEFAULT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol."Tdc_cat_estados_pago_pedido" ALTER COLUMN "Id" SET DEFAULT nextval('dwh_torrecontrol."Tdc_cat_estados_pago_pedido_Id_seq"'::regclass);


--
-- Name: Tdc_cat_lineas_distribucion Id; Type: DEFAULT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol."Tdc_cat_lineas_distribucion" ALTER COLUMN "Id" SET DEFAULT nextval('dwh_torrecontrol."Tdc_cat_lineas_distribucion_Id_seq"'::regclass);


--
-- Name: Tdc_tch_estado_pedidos Id; Type: DEFAULT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol."Tdc_tch_estado_pedidos" ALTER COLUMN "Id" SET DEFAULT nextval('dwh_torrecontrol."Tdc_tch_estado_pedidos_Id_seq"'::regclass);


--
-- Data for Name: AspNetRoleClaims; Type: TABLE DATA; Schema: dlk_torrecontrol; Owner: postgres
--



--
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: dlk_torrecontrol; Owner: postgres
--

INSERT INTO dlk_torrecontrol."AspNetRoles" VALUES ('0', 'Administrators', 'Admin', 'null');
INSERT INTO dlk_torrecontrol."AspNetRoles" VALUES ('1', 'Employees', 'Employee', 'null');
INSERT INTO dlk_torrecontrol."AspNetRoles" VALUES ('2', 'Users', 'User', 'null');


--
-- Data for Name: AspNetUserClaims; Type: TABLE DATA; Schema: dlk_torrecontrol; Owner: postgres
--



--
-- Data for Name: AspNetUserLogins; Type: TABLE DATA; Schema: dlk_torrecontrol; Owner: postgres
--



--
-- Data for Name: AspNetUserRoles; Type: TABLE DATA; Schema: dlk_torrecontrol; Owner: postgres
--

INSERT INTO dlk_torrecontrol."AspNetUserRoles" VALUES ('fbe6c523-68b6-490d-85f7-ec3d55853e08', '0');
INSERT INTO dlk_torrecontrol."AspNetUserRoles" VALUES ('c1894b5d-4b7e-40da-9c0f-c15b5ce1bfa3', '1');
INSERT INTO dlk_torrecontrol."AspNetUserRoles" VALUES ('ed8c43b2-89a8-48ba-9789-37b6581b6f6c', '2');


--
-- Data for Name: AspNetUserTokens; Type: TABLE DATA; Schema: dlk_torrecontrol; Owner: postgres
--



--
-- Data for Name: AspNetUsers; Type: TABLE DATA; Schema: dlk_torrecontrol; Owner: postgres
--

INSERT INTO dlk_torrecontrol."AspNetUsers" VALUES ('fbe6c523-68b6-490d-85f7-ec3d55853e08', 'Sergio', 'Díaz', 'sergio@gmail.com', 'SERGIO@GMAIL.COM', 'sergio@gmail.com', 'SERGIO@GMAIL.COM', false, 'AQAAAAEAACcQAAAAEKT/d52sB4Ns83q1DhpBVkE7L5Qy6/bmdugCpDF+A1whS0qaC12g2YW0UsUYVwWoeg==', 'EXHUW7VX6QWFLAPP2BVNUE2DQXG4AI3J', '2884b9cb-39d4-49eb-bf50-43c84bc6dcec', '666777888', false, false, NULL, true, 0);
INSERT INTO dlk_torrecontrol."AspNetUsers" VALUES ('c1894b5d-4b7e-40da-9c0f-c15b5ce1bfa3', 'Moises', 'Hidalgo', 'moises@gmail.com', 'MOISES@GMAIL.COM', 'moises@gmail.com', 'MOISES@GMAIL.COM', false, 'AQAAAAEAACcQAAAAEOuQxqix6zsnzA32bmfiui/xlXT1NazoIhLSyglnoZwZIGgHDKWnJqQaZVslrXuLPA==', '4CGSVK5VR72DUBFM4MATGQXFQJTCHN56', '38caf576-3fb0-4a91-91ca-d651266d71b7', NULL, false, false, NULL, true, 0);
INSERT INTO dlk_torrecontrol."AspNetUsers" VALUES ('ed8c43b2-89a8-48ba-9789-37b6581b6f6c', 'Javier', 'Cano', 'javier@gmail.com', 'JAVIER@GMAIL.COM', 'javier@gmail.com', 'JAVIER@GMAIL.COM', false, 'AQAAAAEAACcQAAAAEO85tML90G/ncJb1RJes96hBJFB5EcsAGNt/7ZJ17aRg5f1W5NZEEWO6RvZbN2/7GA==', 'DFROVXSJKLSKEZ3CGV32EFA2EWD3YVBQ', '4aa0cf37-b21d-419d-9973-ad56e259285c', NULL, false, false, NULL, true, 0);


--
-- Data for Name: Tdc_cat_estados_devolucion_pedido; Type: TABLE DATA; Schema: dwh_torrecontrol; Owner: postgres
--



--
-- Data for Name: Tdc_cat_estados_envio_pedido; Type: TABLE DATA; Schema: dwh_torrecontrol; Owner: postgres
--



--
-- Data for Name: Tdc_cat_estados_pago_pedido; Type: TABLE DATA; Schema: dwh_torrecontrol; Owner: postgres
--



--
-- Data for Name: Tdc_cat_lineas_distribucion; Type: TABLE DATA; Schema: dwh_torrecontrol; Owner: postgres
--



--
-- Data for Name: Tdc_tch_estado_pedidos; Type: TABLE DATA; Schema: dwh_torrecontrol; Owner: postgres
--



--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."__EFMigrationsHistory" VALUES ('20221112165038_prueba-identity-login-register', '6.0.10');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20221113102825_prueba-migracion-1', '6.0.10');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20221113103005_prueba-migracion-1', '6.0.10');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20221113103330_prueba-migracion-1', '6.0.10');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20221113103437_prueba-migracion-1', '6.0.10');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20221113215918_migracion-dlk-1', '6.0.10');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20221116163026_SeedRoles', '6.0.10');


--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: dlk_torrecontrol; Owner: postgres
--

SELECT pg_catalog.setval('dlk_torrecontrol."AspNetRoleClaims_Id_seq"', 1, false);


--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: dlk_torrecontrol; Owner: postgres
--

SELECT pg_catalog.setval('dlk_torrecontrol."AspNetUserClaims_Id_seq"', 1, false);


--
-- Name: Tdc_cat_estados_devolucion_pedido_Id_seq; Type: SEQUENCE SET; Schema: dwh_torrecontrol; Owner: postgres
--

SELECT pg_catalog.setval('dwh_torrecontrol."Tdc_cat_estados_devolucion_pedido_Id_seq"', 1, false);


--
-- Name: Tdc_cat_estados_envio_pedido_Id_seq; Type: SEQUENCE SET; Schema: dwh_torrecontrol; Owner: postgres
--

SELECT pg_catalog.setval('dwh_torrecontrol."Tdc_cat_estados_envio_pedido_Id_seq"', 1, false);


--
-- Name: Tdc_cat_estados_pago_pedido_Id_seq; Type: SEQUENCE SET; Schema: dwh_torrecontrol; Owner: postgres
--

SELECT pg_catalog.setval('dwh_torrecontrol."Tdc_cat_estados_pago_pedido_Id_seq"', 1, false);


--
-- Name: Tdc_cat_lineas_distribucion_Id_seq; Type: SEQUENCE SET; Schema: dwh_torrecontrol; Owner: postgres
--

SELECT pg_catalog.setval('dwh_torrecontrol."Tdc_cat_lineas_distribucion_Id_seq"', 1, false);


--
-- Name: Tdc_tch_estado_pedidos_Id_seq; Type: SEQUENCE SET; Schema: dwh_torrecontrol; Owner: postgres
--

SELECT pg_catalog.setval('dwh_torrecontrol."Tdc_tch_estado_pedidos_Id_seq"', 1, false);


--
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- Name: Tdc_cat_estados_devolucion_pedido PK_Tdc_cat_estados_devolucion_pedido; Type: CONSTRAINT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol."Tdc_cat_estados_devolucion_pedido"
    ADD CONSTRAINT "PK_Tdc_cat_estados_devolucion_pedido" PRIMARY KEY ("Cod_estado_devolucion");


--
-- Name: Tdc_cat_estados_envio_pedido PK_Tdc_cat_estados_envio_pedido; Type: CONSTRAINT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol."Tdc_cat_estados_envio_pedido"
    ADD CONSTRAINT "PK_Tdc_cat_estados_envio_pedido" PRIMARY KEY ("Cod_estado_envio");


--
-- Name: Tdc_cat_estados_pago_pedido PK_Tdc_cat_estados_pago_pedido; Type: CONSTRAINT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol."Tdc_cat_estados_pago_pedido"
    ADD CONSTRAINT "PK_Tdc_cat_estados_pago_pedido" PRIMARY KEY ("Cod_estado_pago");


--
-- Name: Tdc_cat_lineas_distribucion PK_Tdc_cat_lineas_distribucion; Type: CONSTRAINT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol."Tdc_cat_lineas_distribucion"
    ADD CONSTRAINT "PK_Tdc_cat_lineas_distribucion" PRIMARY KEY ("Cod_linea");


--
-- Name: Tdc_tch_estado_pedidos PK_Tdc_tch_estado_pedidos; Type: CONSTRAINT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol."Tdc_tch_estado_pedidos"
    ADD CONSTRAINT "PK_Tdc_tch_estado_pedidos" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: EmailIndex; Type: INDEX; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE INDEX "EmailIndex" ON dlk_torrecontrol."AspNetUsers" USING btree ("NormalizedEmail");


--
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON dlk_torrecontrol."AspNetRoleClaims" USING btree ("RoleId");


--
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON dlk_torrecontrol."AspNetUserClaims" USING btree ("UserId");


--
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON dlk_torrecontrol."AspNetUserLogins" USING btree ("UserId");


--
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON dlk_torrecontrol."AspNetUserRoles" USING btree ("RoleId");


--
-- Name: RoleNameIndex; Type: INDEX; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE UNIQUE INDEX "RoleNameIndex" ON dlk_torrecontrol."AspNetRoles" USING btree ("NormalizedName");


--
-- Name: UserNameIndex; Type: INDEX; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE UNIQUE INDEX "UserNameIndex" ON dlk_torrecontrol."AspNetUsers" USING btree ("NormalizedUserName");


--
-- Name: IX_Tdc_tch_estado_pedidos_Cod_estado_devolucion; Type: INDEX; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE INDEX "IX_Tdc_tch_estado_pedidos_Cod_estado_devolucion" ON dwh_torrecontrol."Tdc_tch_estado_pedidos" USING btree ("Cod_estado_devolucion");


--
-- Name: IX_Tdc_tch_estado_pedidos_Cod_estado_envio; Type: INDEX; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE INDEX "IX_Tdc_tch_estado_pedidos_Cod_estado_envio" ON dwh_torrecontrol."Tdc_tch_estado_pedidos" USING btree ("Cod_estado_envio");


--
-- Name: IX_Tdc_tch_estado_pedidos_Cod_estado_pago; Type: INDEX; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE INDEX "IX_Tdc_tch_estado_pedidos_Cod_estado_pago" ON dwh_torrecontrol."Tdc_tch_estado_pedidos" USING btree ("Cod_estado_pago");


--
-- Name: IX_Tdc_tch_estado_pedidos_Cod_linea; Type: INDEX; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE INDEX "IX_Tdc_tch_estado_pedidos_Cod_linea" ON dwh_torrecontrol."Tdc_tch_estado_pedidos" USING btree ("Cod_linea");


--
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES dlk_torrecontrol."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES dlk_torrecontrol."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES dlk_torrecontrol."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES dlk_torrecontrol."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES dlk_torrecontrol."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES dlk_torrecontrol."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: Tdc_tch_estado_pedidos FK_Tdc_tch_estado_pedidos_Tdc_cat_estados_devolucion_pedido_Co~; Type: FK CONSTRAINT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol."Tdc_tch_estado_pedidos"
    ADD CONSTRAINT "FK_Tdc_tch_estado_pedidos_Tdc_cat_estados_devolucion_pedido_Co~" FOREIGN KEY ("Cod_estado_devolucion") REFERENCES dwh_torrecontrol."Tdc_cat_estados_devolucion_pedido"("Cod_estado_devolucion");


--
-- Name: Tdc_tch_estado_pedidos FK_Tdc_tch_estado_pedidos_Tdc_cat_estados_envio_pedido_Cod_est~; Type: FK CONSTRAINT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol."Tdc_tch_estado_pedidos"
    ADD CONSTRAINT "FK_Tdc_tch_estado_pedidos_Tdc_cat_estados_envio_pedido_Cod_est~" FOREIGN KEY ("Cod_estado_envio") REFERENCES dwh_torrecontrol."Tdc_cat_estados_envio_pedido"("Cod_estado_envio");


--
-- Name: Tdc_tch_estado_pedidos FK_Tdc_tch_estado_pedidos_Tdc_cat_estados_pago_pedido_Cod_esta~; Type: FK CONSTRAINT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol."Tdc_tch_estado_pedidos"
    ADD CONSTRAINT "FK_Tdc_tch_estado_pedidos_Tdc_cat_estados_pago_pedido_Cod_esta~" FOREIGN KEY ("Cod_estado_pago") REFERENCES dwh_torrecontrol."Tdc_cat_estados_pago_pedido"("Cod_estado_pago");


--
-- Name: Tdc_tch_estado_pedidos FK_Tdc_tch_estado_pedidos_Tdc_cat_lineas_distribucion_Cod_linea; Type: FK CONSTRAINT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol."Tdc_tch_estado_pedidos"
    ADD CONSTRAINT "FK_Tdc_tch_estado_pedidos_Tdc_cat_lineas_distribucion_Cod_linea" FOREIGN KEY ("Cod_linea") REFERENCES dwh_torrecontrol."Tdc_cat_lineas_distribucion"("Cod_linea") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

